name: Deploy to Surge

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build and Deploy
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
      - name: build
        run: hugo --minify
      - name: Deploy to mariai.surge.sh
        run: |
          npm install -g surge
          cp -r public public2
          surge --project public --domain mariai.surge.sh --token ${{secrets.SURGE_TOKEN}}
          surge --project public2 --domain mari-ai.surge.sh --token ${{secrets.SURGE_TOKEN}}
