name: My workflow

on:
  workflow_dispatch:
    push:
      branches:
        - main

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Hugo
        env:
          HUGO_VERSION: 0.100.1
        run: |
          mkdir ~/hugo
          cd ~/hugo
          curl -L "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz" --output hugo.tar.gz
          tar -xvzf hugo.tar.gz
          sudo mv hugo /usr/local/bin
      - name: build
        run: hugo
      - name: Deploy to mariai.surge.sh
        run: |
          npm install -g surge
          cp -r public public2
          surge --project public --domain mariai.surge.sh --token ${{secrets.SURGE_TOKEN}}
          surge --project public2 --domain mari-ai.surge.sh --token ${{secrets.SURGE_TOKEN}}
